# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  sysme_config = release

else ifeq ($(config),debug)
  sysme_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := sysme

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sysme:
ifneq (,$(sysme_config))
	@echo "==== Building sysme ($(sysme_config)) ===="
	@${MAKE} --no-print-directory -C . -f sysme.make config=$(sysme_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f sysme.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sysme"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"